### ISSUE TITLE
Need a logo!

### ISSUE THREAD

**Issue by zeyadetman** [zeyadetman/bankeeper#17]

**Comment by egodyston** [comment]
I could help you with that if you would provide some more information :)

**Comment by mirzazulfan** [comment]
Hi @zeyadetman ,, What about this ? If you need something else please let me know. 
![bankeeper](https://user-images.githubusercontent.com/36124339/48475640-cfab0a00-e82f-11e8-8431-3f575346681f.png)

**Comment by zeyadetman** [comment]
> Hi @zeyadetman ,, What about this ? If you need something else please let me know.
> ![bankeeper](https://user-images.githubusercontent.com/36124339/48475640-cfab0a00-e82f-11e8-8431-3f575346681f.png)

Great one! But can you change the color to be `#fc3` or close to it? @mirzazulfan

**Comment by mirzazulfan** [comment]
Thanks for your response @zeyadetman .. sure, i'll change and send you all files.

**Comment by mirzazulfan** [comment]
Hi @zeyadetman . I've created a pr #21 .. Here's your [files](https://drive.google.com/drive/folders/1eBG0HW16A5CSI2_7BkIZZdAAy7Et4Nq2?ogsrc=32)

**Comment by zeyadetman** [comment]
Thanks @mirzazulfan I appreciated that!
