### ISSUE TITLE
Refactor the `import` paths

### ISSUE THREAD

**Issue by zeyadetman** [zeyadetman/bankeeper#19]
Replace the `../../` style by set the root.

**Comment by luizbaldi** [comment]
Hi, I'm taking this one :)

**Comment by luizbaldi** [comment]
Exactly! The main reason I personally dislike this approach is because we lost the autocomplete from the editor.
I'm my experience the best solution for this scenario is using the module-resolver from babel, but since this project is using CRA it'll increase complexity. I'll see what I can do :)
